### PR TITLE
Desktop View

### PR DESCRIPTION
**Pull request by dfosco**
- [x] Desktop view not able to render App within (Bug - [#53](https://github.com/vtex-apps/editor/issues/53))
 - [x] ~~Add toggle between mobile and desktop renders — or render both in a single component~~
 - [ ] Refactor Mobile SidePanel into a Desktop Sidebar
 - [ ] Rethink editor mode basic interface for desktop usage
 - [x] Rename AppsView to GalleryView (Enhancement - [#51](https://github.com/vtex-apps/editor/issues/51))

### CODE REVIEW

**Comment by brenoc** [comment]
@dfosco we need to restructure the Editor interface. I was profiling and its performance it's shitty :( mostly because of the AppContainer height that is calculated getting the height of the viewport. We should structure to use good CSS and HTML.

One way to do this is how they managed to do it perfectly here:
http://www.idangero.us/framework7/

Also, we need to end with MobileContainer and DesktopContainer and seek for a responsive alternative.

**Comment by dfosco** [comment]
@brenoc I was talking to @tamorim during our bus trip about how MobileContainer and DesktopContainer are opposite to a responsive approach — we'll have to ditch them, indeed.

Let's take this Desktop View effort and rebuild it the right way while still keeping it MVP — no sense to build on top of a rotten base, but this architectural refactor can't last more than a couple of days.

**Comment by brenoc** [comment]
@dfosco totally :+1:

**Comment by dfosco** [comment]
Deprecated  
¯\_(ツ)_/¯

**Pull request closed without merging**
