### PR TITLE
Add autoprefixer loader

### LINKED ISSUE #39: Install autoprefixer

### PR DESCRIPTION
**Pull request by brenoc**
Fix #39

### CODE REVIEW

**Comment by dfosco** [comment]
#39 is closed. All is well in the kingdom.

@brenoc, can you replicate this to all apps later?

**Comment by brenoc** [comment]
@dfosco I would love help :grin:

**Comment by dfosco** [comment]
@brenoc Will do, I think I'm able to grab the changes :)

**Comment by brenoc** [comment]
@dfosco you closed but didn't merge this branch haha shoul I do it?

**Pull request merged**
