### PR TITLE
Improve layout for ActionBar put on top

### PR DESCRIPTION
**Pull request by dfosco**
Still needs for every editor to have their top padding bumped a bit on `storefront-theme` or their respective repos, as the ActionBar is taller now.

### CODE REVIEW

**Comment by bellacorbo** [comment]
@dfosco the padding is defined in the Editor Panel component, so there's no need to change padding individually in every editor component. As soon as this PR is closed, I'll adapt the editor for the new changes. 

And what about the title font style? Don't you think we should change it? I see the title doesn't appear in the component you used as an example (did you add the title prop?), but here's how it looks now: 

actionbar

**Comment by dfosco** [comment]
@bellacorbo Oh right, forgot about the title... to be honest, I don't think it'll fit in there unless I make the buttons round.

That or the title goes below in another bar, but that kind sucks.

I'll try something out and commit here.

**Comment by brenoc** [comment]
@dfosco maybe the editor developer sets the title inside the editor, ex:

```js
render() {
  const ActionBar = this.props.ActionBar;

  return (
    <div>
      <ActionBar onSave={this.onSave.bind(this)}/>
      <h1>Component Title here!</h1>
      <form>
        ...
      </form>
    </div>
  )
}
```

Like what "Configuração Geral" is doing.

**Comment by dfosco** [comment]
This got me thinking... should we make a `editor.panel` wrapper as well?

  

It could be good in terms of achieving consistency between app editors — I
would hate for our modular CMS to have shitty and/or inconsistent interfaces
between each editor where the user has to relearn simple controls.

  

I think a wrapper that locks the action bar and title &amp; a suggested
styleguide with default form elements for your editor would do the trick.

> On Nov 16 2015, at 8:00 pm, Breno Calazans &lt;notifications@github.com&gt;
wrote:  

>

> [@dfosco](https://github.com/dfosco) maybe the editor developer sets the
title inside the editor, ex:

>  
>  
>     render() {

>       const ActionBar = this.props.ActionBar;

>  
>       return (

>         <div>

>           <ActionBar onSave={this.onSave.bind(this)}/>

>           <h1>Component Title here!</h1>

>           <form>

>             ...

>           </form>

>         </div>

>       )

>     }

>

> Like what "Configuração Geral" is doing.

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/vtex-
apps/storefront-editor/pull/42#issuecomment-157202228).

**Comment by bellacorbo** [comment]
@dfosco I like the idea!

**Comment by brenoc** [comment]
@dfosco @bellacorbo EditorPanel **is** a component wrapper for the editor, it automatically wraps the editor providing and *locking* the ActionBar.

**Comment by dfosco** [comment]
@brenoc @bellacorbo What's still pending here?

**Comment by brenoc** [comment]
editor

@dfosco I miss the text label of the buttons. Why did you think they shouldn't have any?

**Comment by dfosco** [comment]
@brenoc Aesthetically nicer and still think they convey the right meaning — but we could revert if necessary. Would love to user-test this soon :)

**Comment by bellacorbo** [comment]
@dfosco wee need to close this branch. Would you review this PR? To save you the trouble, this is how the action bar looks now: 
actionbar

**Comment by tamorim** [comment]
@dfosco is this ready?

**Comment by dfosco** [comment]
@tamorim I'm not able to run the editor right now, want to take a look at it one more time to make sure it's :ok_hand:

**Comment by dfosco** [comment]
@tamorim As far as I know, it's done — there are layout improvements I can make and me and @bellacorbo freezed a feature along the way, but we're good to go.

We'll close it tomorrow :grinning:

**Comment by tamorim** [comment]
@dfosco beautiful! :zap:

**Comment by dfosco** [comment]
https://www.youtube.com/watch?v=tJ7z5CUsrbk :facepunch: :gun: :zap:

**Pull request merged**
