### PR TITLE
Component Configuration Flow for Editor CMS (Plug & Play)

### PR DESCRIPTION
**Pull request by dfosco**
**Plug & Play Prototype [(Happy Path)](https://drive.google.com/a/vtex.com.br/file/d/0B5T0KIQagU1oMkp6cUhYazBCb2M/view?usp=sharing)**

 - [x] `Wizard Status` Component
   - [x] Rethink progress indicator and **[Adicionado]** badge for `WizardStatus`
   - [x] Introduce flow with some kind of text indicating the possible task @ the view

 - [x] `Wizard Navigation` Component

 - [x] `Select Component` Component
   - [x] Focussed `ComponentBox`
   - [x] Configured `ComponentBox`
   - [x] Disabled `ComponentBox`
   - [x] Indicate selected route for configured `ComponentBox`
   - [x] Custom event for bringing `RouteList` feeding component props  (`feature/editor-cms`)

 - [x] `Select Route`
   - [x] `RouteStatus` collapsing at the bottom of `SidePanel`
   - [x] Flexbox rendering bug when `RouteStatus` comes into view (`feature/editor-cms`)
   - [x] Use ReactCSSTransitions when rendering `RouteStatus`  (`feature/editor-cms`)
   - [x] Overlay on top of `RouteList` that closes it
   - [x] Lock `SidePanel` scroll when `RouteList` is open

 - [x] `Select Apps` 
   - [x] View listing all components, separated by apps

---

**Later Iterations**

 - [ ] `Select Apps` 
   - [ ] Make Apps and Components visually different

 - [ ] `Edit Mode`
   - [ ] Refactor nature of edit button during Component Wizard — make it a toggle
   - [ ] Make intention special color highlight secondary color on hover at the component, not selection
   - [ ] Make drag areas clearer

### CODE REVIEW

**Comment by dfosco** [comment]
@storefront_team The user flow for instancing components (from now on described as **plugging**, not **configuring** components, to avoid confusion) through drag 'n drop has two states, listed below with a brief description for the behavior of both.

```javascript
state = {
    // Initial State    
    isPluggingComponent: false
  }
```

**Viewing State (initial state)** 
 - Only components available for plugging in the current route are draggable
 - Available/Unavailable components are color coded ( :large_blue_circle: / :black_circle: )
 - Clicking unavailable ones opens Route Selector
 - Clicking available ones switches into `Plugging State`

**Plugging State**
 - Highlights selected component and area with matching `intention` with :red_circle: color
 - Marks other available components and all other available areas with :large_blue_circle: color
 **Important:** This state is described under the assumption that area intentions are no longer exclusive, and allow other “non-prioritary” components to be plugged on them

---

This flow was thoroughly discussed with @tamorim today and I'm thrilled to prototype it ASAP — this is the first time all the pieces are clicking, at least for me. Let's take some time to discuss it tomorrow because it assumes changes in the backend that need to be reviewed by @amoreira and @brunoabreu 

cheers!
:smile:

**Comment by dfosco** [comment]
@storefront_team The user flow for instancing components (from now on described as **plugging**, not **configuring** components, to avoid confusion) through drag 'n drop has two states, listed below with a brief description for the behavior of both.

```javascript
state = {
    // Initial State    
    isPluggingComponent: false
  }
```

**Viewing State (initial state)** 
 - Only components available for plugging in the current route are draggable
 - Available/Unavailable components are color coded ( :large_blue_circle: / :black_circle: )
 - Clicking unavailable ones opens Route Selector
 - Clicking available ones switches into `Plugging State`

**Plugging State**
 - Highlights selected component and area with matching `intention` with :red_circle: color
 - Marks other available components and all other available areas with :large_blue_circle: color
 - Unavailable components are still color coded as :black_circle: 

**Important:** This state is described under the assumption that area intentions are no longer exclusive, and allow other “non-prioritary” components to be plugged on them. Let's talk about this, team!

---

This flow was thoroughly discussed with @tamorim today and I'll try to prototype it as much as I can tomorrow — this is the first time all the pieces of the flow are clicking, at least for me. Let's take some time to discuss it tomorrow because it assumes changes in the backend that need to be agreed upon by @amoreira and @brunoabreu 

cheers!
:smile:

**Comment by dfosco** [comment]
@tamorim Done :dancers:

**Comment by tamorim** [comment]
@dfosco moved to https://github.com/vtex-apps/editor/pull/66

**Pull request closed without merging**
